export const config = {
  compilerOptions: {
    target: "es6",
    module: "commonjs",
    moduleResolution: "node",
    allowSyntheticDefaultImports: true,
    allowJs: true,
    importHelpers: true,
    jsx: "react",
    alwaysStrict: true,
    forceConsistentCasingInFileNames: true,
    noFallthroughCasesInSwitch: true,
    noImplicitReturns: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noImplicitAny: false,
    noImplicitThis: false,
    strictNullChecks: false,
  },
  include: ["**/*"],
  exclude: ["node_modules", "build"],
} as const;
